platform :ios, '10.0'
use_frameworks! :linkage => :static

source 'https://github.com/CocoaPods/Specs.git'

def pod_Common
  pod 'JSMediaBrowser', :path => '..'
  pod 'QMUIKit', '~> 4.2.1' 
  pod 'SnapKit', '~> 5.0.0'
  pod 'SDWebImage', '~> 5.10.2'
end

target 'JSMediaBrowserExample' do
  pod_Common
  # 调试工具
  pod 'LookinServer', :configurations => ['Debug']
  pod 'MLeaksFinder', :configurations => ['Debug']
end

target 'JSMediaBrowserExampleMacOS' do
  pod_Common
end
