platform :ios, "13.0"
use_frameworks! :linkage => :dynamic

def pod_Common
  pod "JSMediaBrowser", :path => "../", :subspecs => [
    "Business", 
    "MediaImageForSDWebImage", 
    "MediaImageForPHLivePhoto", 
    "MediaImageForKingfisher"
  ]
  pod "QMUIKit"
  pod "SnapKit"
  pod "Then"
  pod 'SwiftLint', :configurations => ['Debug']
  pod "LookinServer", :subspecs => ['Swift'], :configurations => ["Debug"]
  pod "MLeaksFinder", :git => "https://github.com/Tencent/MLeaksFinder.git", :configurations => ["Debug"]
end

target "JSMediaBrowserExample" do
  pod_Common
end

target "JSMediaBrowserExampleMacOS" do
  pod_Common
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
    end
  end
end