platform :ios, '10.0'
use_frameworks! :linkage => :static

source 'https://github.com/CocoaPods/Specs.git'

def pod_Common
  pod 'JSMediaBrowser', :path => '..', :subspecs => ['BusinessForImage', 'BusinessForVideo', 'MediaImageForSDWebImage']
  pod 'QMUIKit'
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'Kingfisher'
end

target 'JSMediaBrowserExample' do
  pod_Common
  # 调试工具
  pod 'LookinServer', :configurations => ['Debug']
  pod 'MLeaksFinder', :configurations => ['Debug']
  pod "FBRetainCycleDetector", :git => "https://github.com/jiasongs/FBRetainCycleDetector.git", :configurations => ["Debug"]
end

target 'JSMediaBrowserExampleMacOS' do
  pod_Common
end
